from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('msgs/*.c') + Glob('*.cpp')
CPPPATH = [cwd, cwd + '/msgs']

group = DefineGroup('Micro-XRCE-DDS-Client', src, depend = ['MICRO_XRCE_DDS_CLIENT_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
